name: Check and Send Notifications

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Npm Install
        run: npm install
      - name: Check and Send Notifications
        run: node checkNotifications.ts
        env:
          FCM_TOKEN: ${{secrets.FCM_TOKEN}}
      - name: Push to Master branch
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          build_dir: ./
          target_branch: master
          commit_message: 'Updates Raised Notifications'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
