name: Check and Send Notifications

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Setup Axios
        run: npm install axios
      - name: Check and Send Notifications
        run: node checkNotifications.ts
        env:
          FCM_TOKEN: ${{secrets.FCM_TOKEN}}
