name: Check and Send Notifications

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '*/1 * * * *'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1.4.3
      - name: Check and Send Notifications
        run: node checkNotifications.ts
        env:
          FCM_TOKEN: ${{secrets.FCM_TOKEN}}
